apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus
    prometheus: cluster 
spec:
  alerting:
    alertmanagers:
      - namespace: zcp-system
        name: alertmanager
        port: http
  additionalScrapeConfigs:
    name: additional-scrape-configs 
    key: prometheus-additional.yaml
  baseImage: "prom/prometheus"
  paused: false
  replicas: 1
  logLevel: info
  routePrefix: "/"
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: 
    matchLabels:
      prometheus: cluster 
  ruleSelector: 
    matchLabels:
      prometheus: cluster 
  ruleNamespaceSelector: {}
  resources:
    requests:
      memory: 1Gi
  externalLabels:
    env: sk-cps-ops-dev
  enableAdminAPI: true
  retention: 15d
  scrapeInterval: 10s
  evaluationInterval: 10s
  version: "v2.7.0"
  securityContext:
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 20Gi
