apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    app: prometheus
    prometheus: cluster 
spec:
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    matchNames:
      - "zcp-system"
  endpoints:
    - port: prometheus
      interval: 10s
