kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-state-metrics
    prometheus: cluster
  name: kube-state-metrics
spec:
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  namespaceSelector:
    matchNames:
      - "zcp-system"
  endpoints:
    - port: http-metrics
      interval: 10s
      honorLabels: true
